name: mhu_props
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^3.1.0
  fixnum: ^1.1.0
  dart_scope_functions: ^0.1.6
  

