name: mhu_blob_cache
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  dart_scope_functions: ^0.1.6
  path_provider: ^2.1.3
  path: ^1.9.0
  idb_shim: ^2.4.1+1
  logger: ^2.2.0
  
  crypto: ^3.0.3
  
  

